@base_url = http://localhost:3000/api

###
GET {{base_url}}/

###
GET {{base_url}}/admin/test

###
POST {{base_url}}/admin/sign-up
Content-Type: application/json

{
    "email": "123@gmail.com",
    "password": "1111"
}

### Login pass case
GET {{base_url}}/admin/log-in
Content-Type: application/json

{
    "email": "123@gmail.com",
    "password": "1111"
}

### Login fail case
GET {{base_url}}/admin/log-in
Content-Type: application/json

{
    "email": "12345@gmail.com",
    "password": "1111"
}